"""
Export meeting results (summary, decisions, action items, agenda status)
to Markdown and PDF formats.
"""

from __future__ import annotations
from datetime import datetime
from typing import Optional
from fpdf import FPDF

def _g(obj, key, default = ""):
    if obj is None:
        return default
    if isinstance(obj, dict):
        return obj.get(key, default)
    return getattr(obj, key, default)

# -----------------------------------------------------------------------------
# Markdown Export
# -----------------------------------------------------------------------------

def format_meeting_markdown(
        meeting_title: str,
        meeting_date: Optional[str],
        summary: str,
        decisions: list,
        action_items: list,
        agenda_items: list,
) -> str:
    lines = [f"# Meeting Minutes - {meeting_title}"]
    if meeting_date:
        lines.append(f"*{meeting_date}*")
    lines.append("")

    lines.append("## Summary")
    lines.append(summary.strip() if summary else "_No summary generated._")
    lines.append("")

    lines.append("## Decisions")
    if decisions:
        for d in decisions:
            text = _g(d, "decision") or _g(d, "text")
            context = _g(d, "context")
            lines.append(f"- **{text}** - _{context}_" if context else f"- **{text}**")
    else:
        lines.append("_No decisions recorded._")
    lines.append("")

    lines.append("## Action Items")
    if action_items:
        lines.append("| Task | Assignee | Deadline |")
        lines.append("|---|---|---|")
        for a in action_items:
            task = _g(a, "task", "")
            assignee = _g(a, "assignee") or "_unassigned_"
            deadline = _g(a, "deadline") or "_no deadline_"
            lines.append(f"| {task} | {assignee} | {deadline} |")
    else:
        lines.append("_No action items recorded._")
    lines.append("")

    lines.append("## Agenda Coverage")
    status_labels = {
        "covered" : "✅ Covered",
        "partially_covered": "⚠️ Partially Covered",
        "not_covered": "❌ Not Covered",
    }
    if agenda_items:
        for item in agenda_items:
            agenda_text = _g(item, "item") or _g(item, "agenda_item")
            status = _g(item, "status")
            status_str = status.value if hasattr(status, "value") else str(status)
            evidence = _g(item, "evidence")
            lines.append(f"- **{agenda_text}** - {status_labels.get(status_str, status_str)}")
            if evidence:
                lines.append(f"  - _Evidence: {evidence}_")
    else:
        lines.append("_No agenda provided._")
    lines.append("")
    lines.append("---")
    lines.append(f"_Generated by MeetingMind on {datetime.now().strftime('%Y-%m-%d %H:%M')}_")
    return "\n".join(lines)

# ---------------------------------------------------------------------------
# PDF export
# ---------------------------------------------------------------------------

class MeetingPDF(FPDF):
    GUNMETAL = (34, 40, 45)
    STEEL_GREY = (90, 100, 108)
    VU_GREEN = (60, 179, 113)
    INSTRUMENT_BLUE = (70, 130, 180)

    def header(self):
        self.set_fill_color(*self.GUNMETAL)
        self.rect(0, 0, 210, 20, style="F")
        self.set_text_color(255, 255, 255)
        self.set_font("Helvetica", "B", 14)
        self.set_xy(10, 6)
        self.cell(0, 8, "MEETINGMIND -- MEETING MINUTES", ln=1)
        self.ln(8)
        self.set_text_color(0, 0, 0)

    def footer(self):
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*self.STEEL_GREY)
        self.cell(0, 10, f"Page {self.page_no()}", align="C")


def export_meeting_pdf(
        meeting_title: str,
        meeting_date: Optional[str],
        summary: str,
        decisions: list,
        action_items: list,
        agenda_items: list,
) -> bytes:
        pdf = MeetingPDF()
        pdf.set_auto_page_break(auto=True, margin=18)
        pdf.add_page()
        pdf.set_font("Helvetica", "B", 16)
        pdf.cell(0, 10, meeting_title, ln=1)
        if meeting_date:
            pdf.set_font("Helvetica", "I", 10)
            pdf.set_text_color(*MeetingPDF.STEEL_GREY)
            pdf.cell(0, 6, meeting_date, ln=1)
            pdf.set_text_color(0, 0, 0)
        pdf.ln(4)

        def section_title(title, color):
            pdf.set_font("Helvetica", "B", 12)
            pdf.set_text_color(*color)
            pdf.cell(0, 8, title, ln=1)
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", "", 10)

        section_title("SUMMARY", MeetingPDF.INSTRUMENT_BLUE)
        pdf.multi_cell(0, 6, summary.strip() if summary else "No summary generated.")
        pdf.set_x(pdf.l_margin)
        pdf.ln(2)

        section_title("DECISIONS", MeetingPDF.VU_GREEN)
        if decisions:
            for d in decisions:
                text = _g(d, "decision") or _g(d, "text")
                context = _g(d, "context")
                pdf.set_font("Helvetica", "B", 10)
                pdf.multi_cell(0, 6, f"- {text}")
                pdf.set_x(pdf.l_margin)
                if context:
                    pdf.set_font("Helvetica", "I", 9)
                    pdf.set_text_color(*MeetingPDF.STEEL_GREY)
                    pdf.multi_cell(0, 5, f"  {context}")
                    pdf.set_x(pdf.l_margin)
                    pdf.set_text_color(0, 0, 0)
        else:
            pdf.multi_cell(0, 6, "No decisions recorded.")
            pdf.set_x(pdf.l_margin)
        pdf.ln(2)

        section_title("ACTION ITEMS", MeetingPDF.VU_GREEN)
        if action_items:
            col_widths = [90, 45, 45]
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_fill_color(*MeetingPDF.GUNMETAL)
            pdf.set_text_color(255, 255, 255)
            for w, h in zip(col_widths, ["Task", "Assignee", "Deadline"]):
                pdf.cell(w, 7, h, border=1, fill=True)
            pdf.ln()
            pdf.set_text_color(0, 0, 0)
            pdf.set_font("Helvetica", "", 9)
            for a in action_items:
                task = str(_g(a, "task", ""))
                assignee = str(_g(a, "assignee") or "unassigned")
                deadline = str(_g(a, "deadline") or "no deadline")
                pdf.cell(col_widths[0], 7, task[:55], border=1)
                pdf.cell(col_widths[1], 7, assignee[:25], border=1)
                pdf.cell(col_widths[2], 7, deadline[:25], border=1)
                pdf.ln()
        else:
            pdf.multi_cell(0, 6, "No action items recorded.")
            pdf.set_x(pdf.l_margin)
        pdf.ln(2)

        section_title("AGENDA COVERAGE", MeetingPDF.INSTRUMENT_BLUE)
        status_symbols = {
            "covered": "[COVERED]",
            "partially_covered": "[PARTIAL]",
            "not_covered": "[NOT COVERED]",
        }
        if agenda_items:
            for item in agenda_items:
                agenda_text = _g(item, "item") or _g(item, "agenda_item")
                status = _g(item, "status")
                status_str = status.value if hasattr(status, "value") else str(status)
                evidence = _g(item, "evidence")
                label = status_symbols.get(status_str, status_str)
                pdf.set_font("Helvetica", "B", 10)
                pdf.multi_cell(0, 6, f"{label} {agenda_text}")
                pdf.set_x(pdf.l_margin)
                if evidence:
                    pdf.set_font("Helvetica", "I", 9)
                    pdf.set_text_color(*MeetingPDF.STEEL_GREY)
                    pdf.multi_cell(0, 5, f"  {evidence}")
                    pdf.set_x(pdf.l_margin)
                    pdf.set_text_color(0, 0, 0)
        else:
            pdf.multi_cell(0, 6, "No agenda provided.")
            pdf.set_x(pdf.l_margin)

        output = pdf.output()
        return bytes(output) if isinstance(output, (bytes, bytearray)) else output.encode("latin-1")